export const invitations = [
  {
    id: 'futursmaries',
    name: 'Florent et Agnès',
    people: ['Florent', 'Agnès'],
    ages: { Florent: '18 - 75 ans', Agnès: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: [],
    placeholderComment: '',
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mumsiepascal',
    name: 'Mary and Pascal',
    people: ['Mary', 'Pascal'],
    ages: { Mary: '18 - 75 ans', Pascal: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies:
      "This is where you have to write that you're allergic to seafood for example. ;)",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'maminou',
    name: 'Marie-Ange',
    people: ['Marie-Ange'],
    ages: { 'Marie-Ange': '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Un petit message pour la future Agnès B. et ton Fils ?',
    placeholderAllergies:
      'Note ici tes éventuelles allergies. Genre paracetamol, ...',
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'richy',
    name: 'Richard et Nathalie',
    people: ['Richard', 'Nathalie'],
    ages: { Richard: '18 - 75 ans', Nathalie: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Même un mot c'est cool ! :)",
    placeholderAllergies: "Allergique à l'avion, quoi d'autre ? ;)",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'lulufamily',
    name: 'Lucile, Gwen, Rosa et Nina',
    people: ['Lucile', 'Gwen', 'Rosa', 'Nina'],
    ages: {
      Lucile: '18 - 75 ans',
      Gwen: '18 - 75 ans',
      Rosa: '13 - 17 ans',
      Nina: '4 - 12 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: ['Rosa', 'Nina'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: "Nina est allérgique à la mayo, quoi d'autre ? ;)",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'empegues',
    name: 'Pau et John',
    people: ['Pau', 'John'],
    ages: { Pau: '18 - 75 ans', John: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: 'Écrire ici la forme souhaitée du PauPauDium. ;)',
    placeholderAllergies: "John, t'as pas le droit de mettre le PSG ici !",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mathourom',
    name: 'Mathou, Rominou et Ariane',
    people: ['Mathou', 'Rominou', 'Ariane'],
    ages: {
      Mathou: '18 - 75 ans',
      Rominou: '18 - 75 ans',
      Ariane: '0 - 3 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Ariane'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: "Allergiques au champagne, quoi d'autre ? ;)",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'maya',
    name: 'Maya',
    people: ['Maya'],
    ages: { Maya: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Write here a little message for us or the title of your favorite Johnny song. ;)',
    placeholderAllergies: 'Is fish OK for you ?',
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'biboune',
    name: 'Boris et Cathia',
    people: ['Boris', 'Cathia'],
    ages: { Boris: '18 - 75 ans', Cathia: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: 'Biboune, Cartouche, un petit message pour nous ?',
    placeholderAllergies:
      "Hormis l'allérgie à tout ce qui est alcool, y'a quoi ?",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'joeva',
    name: 'Jo et Eva',
    people: ['Jo', 'Eva', 'Lily Baby', 'Flore'],
    ages: {
      Jo: '18 - 75 ans',
      Eva: '18 - 75 ans',
      'Lily Baby': '0 - 3 ans',
      Flore: '18 - 75 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Lily Baby'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies:
      "Précisez ici votre régime. Choisisez ce que vous voulez au cas où le traiteur ne pourrait pas adapter le menu. Jo, le poisson ne sera pas issu d'élevages. ;)",
    isAnswered: true,
    invitedTo: {
      cityHall: true,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'gmgd',
    name: 'Grandma and Granddad',
    people: ['Grandma', 'Granddad'],
    ages: { Grandma: '75 ans et +', Granddad: '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: 'Any allergies we might not know about ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mepe',
    name: 'Mémère et Pépère',
    people: ['Mémère', 'Pépère'],
    ages: { Mémère: '75 ans et +', Pépère: '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'tanteadele',
    name: 'Tante Adèle',
    people: ['Tante Adèle'],
    ages: { 'Tante Adèle': '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'auntiemoni',
    name: 'Auntie Moni',
    people: ['Moni Abraham'],
    ages: { 'Moni Abraham': '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: 'Any allergies we might not know about ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mamieva',
    name: 'Eva',
    people: ['Mamie Eva'],
    ages: { 'Mamie Eva': '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mulots',
    name: 'Line et Raphaël',
    people: ['Line', 'Raphaël'],
    ages: { Line: '18 - 75 ans', Raphaël: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'auntiesismark',
    name: 'Auntie Sis and Uncle Mark',
    people: ['Auntie Sis', 'Uncle Mark'],
    ages: { 'Auntie Sis': '18 - 75 ans', 'Uncle Mark': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: 'Any allergies we might not know about ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'plauds',
    name: 'Tonton François et Tata Andrée',
    people: ['Tonton François', 'Tata Andrée'],
    ages: { 'Tonton François': '75 ans et +', 'Tata Andrée': '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'parrain',
    name: 'Jean-Yves',
    people: ['Jean-Yves'],
    ages: { 'Jean-Yves': '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: 'Un petit mot pour nous avant le marriage ?',
    placeholderAllergies:
      "Parrain, écris tes allérgies ici. Désolé, il n'y aura pas de saumon fumé.",
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'tatajaja',
    name: 'Jannick',
    people: ['Jannick'],
    ages: { Jannick: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'abeilles',
    name: 'Jocelyne et Jean-François',
    people: ['Jocelyne', 'Jean-François L'],
    ages: { Jocelyne: '18 - 75 ans', 'Jean-François L': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'airbnb',
    name: 'Jacques et Christiane',
    people: ['Jacques', 'Christiane'],
    ages: { Jacques: '18 - 75 ans', Christiane: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'fin',
    name: 'Finlay',
    people: ['Finlay'],
    ages: { Finlay: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: 'Any allergies we might not know about ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'stew',
    name: 'Stewart',
    people: ['Stewart'],
    ages: { Stewart: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: 'Any allergies we might not know about ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'voilier',
    name: 'Guillaume, Natacha, Enola et Malo',
    people: ['Guillaume', 'Natacha', 'Enola', 'Malo'],
    ages: {
      Guillaume: '18 - 75 ans',
      Natacha: '18 - 75 ans',
      Enola: '13 - 17 ans',
      Malo: '4 - 12 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Enola', 'Malo'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'pauline',
    name: 'Pauline',
    people: ['Pauline B'],
    ages: { 'Pauline B': '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'tomtom',
    name: 'Thomas',
    people: ['Thomas'],
    ages: { Thomas: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'claquesdtg',
    name: 'Eloïse et Edouard',
    people: ['Eloïse', 'Edouard'],
    ages: { Eloïse: '18 - 75 ans', Edouard: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      "Un petit message pour qu'on se prépare au mieux ? Je crois tout de même qu'Agnès ne veut pas de baffe durant le mariage. :'(",
    placeholderAllergies:
      'Très cher Avocate, note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'filleule',
    name: 'Solène',
    people: ['Solène L'],
    ages: { 'Solène L': '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Filleule, note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'fleur',
    name: 'Fleur',
    people: ['Fleur', 'Loan'],
    ages: { Fleur: '18 - 75 ans', Loan: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'marine',
    name: 'Marine',
    people: ['Marine'],
    ages: { Marine: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'anne',
    name: 'Anne',
    people: ['Anne', 'Johann'],
    ages: { Anne: '18 - 75 ans', Johann: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies:
      'Précise ici ton régime et choisis ce que tu veux au cas où le traiteur ne pourrait pas adapter le menu.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'nicoise',
    name: 'Fanny',
    people: ['Fanny'],
    ages: { Fanny: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'rush',
    name: 'Nabil',
    people: ['Nabil'],
    ages: { Nabil: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'florence',
    name: 'Din et Solène',
    people: ['Din', 'Solène'],
    ages: { Din: '18 - 75 ans', Solène: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: 'Vous serez les prochains ! Un petit mot pour nous ?',
    placeholderAllergies: 'Hormis manger rapidement ?',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'hoarau',
    name: 'Patrick et Mannue',
    people: ['Patrick', 'Mannue'],
    ages: { Patrick: '18 - 75 ans', Mannue: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'soireebde',
    name: 'Thibaud, Christelle et Ambre',
    people: ['Thibaud', 'Christelle', 'Ambre'],
    ages: {
      Thibaud: '18 - 75 ans',
      Christelle: '18 - 75 ans',
      Ambre: '0 - 3 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Ambre'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'john',
    name: 'John et Laura',
    people: ['John Paris', 'Laura John Paris'],
    ages: { 'John Paris': '18 - 75 ans', 'Laura John Paris': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'obrigado',
    name: 'Denise et Lang',
    people: ['Denise', 'Lang'],
    ages: { Denise: '18 - 75 ans', Lang: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'miami2',
    name: 'Cécile',
    people: ['Cécile'],
    ages: { Cécile: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies:
      'Précise ici ton régime et choisis ce que tu veux au cas où le traiteur ne pourrait pas adapter le menu.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'ephebe',
    name: 'Val',
    people: ['Val'],
    ages: { Val: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "A t'y un message pour nous le gars valentin ?",
    placeholderAllergies: "Ki k's'est qu'il a comme alergies c'lui-ci ?",
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'lolocaillou',
    name: 'Laura et Pierre',
    people: ['Laura L', 'Pierre M'],
    ages: { 'Laura L': '18 - 75 ans', 'Pierre M': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'nigzyfamily',
    name: 'Yannig, Akari, Lanna, Liam et Leyanna',
    people: ['Yannig', 'Akari', 'Lanna', 'Liam', 'Leyanna'],
    ages: {
      Yannig: '18 - 75 ans',
      Akari: '18 - 75 ans',
      Lanna: '4 - 12 ans',
      Liam: '4 - 12 ans',
      Leyanna: '4 - 12 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Lanna', 'Liam', 'Leyanna'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'lilyflojuju',
    name: 'Lily, Florian et Jules',
    people: ['Lily', 'Florian', 'Jules'],
    ages: { Lily: '18 - 75 ans', Florian: '18 - 75 ans', Jules: '0 - 3 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Jules'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'colombes',
    name: 'Alix et Valentin',
    people: ['Alix', 'Valentin'],
    ages: { Alix: '18 - 75 ans', Valentin: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'flosimon',
    name: 'Florence et Simon',
    people: ['Florence', 'Simon'],
    ages: { Florence: '18 - 75 ans', Simon: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'malou',
    name: 'Marie-Lou et Nikodem',
    people: ['Marie-Lou', 'Nikodem'],
    ages: { 'Marie-Lou': '18 - 75 ans', Nikodem: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mathias',
    name: 'Mathias',
    people: ['Mathias'],
    ages: { Mathias: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Note ici tes éventuelles allergies. :)',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'kaga',
    name: 'Maruina et Yann',
    people: ['Maruina', 'Yann'],
    ages: { Maruina: '18 - 75 ans', Yann: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'orny',
    name: 'Ornella et Pierre',
    people: ['Ornella', 'Pierre R'],
    ages: { Ornella: '18 - 75 ans', 'Pierre R': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'cocopepito',
    name: 'Coralie et Giovanni',
    people: ['Coralie', 'Giovanni'],
    ages: { Coralie: '18 - 75 ans', Giovanni: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mae',
    name: 'Maëva, Quentin, Malone et Alix Baby',
    people: ['Maëva', 'Quentin', 'Malone', 'Alix Baby'],
    ages: {
      Maëva: '18 - 75 ans',
      Quentin: '18 - 75 ans',
      Malone: '4 - 12 ans',
      'Alix Baby': '0 - 3 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Malone', 'Alix Baby'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'jess',
    name: 'Jessica, Gregory et Erwann',
    people: ['Jessica', 'Antoine N', 'Gregory', 'Erwann'],
    ages: {
      Jessica: '18 - 75 ans',
      'Antoine N': '18 - 75 ans',
      Gregory: '4 - 12 ans',
      Erwann: '4 - 12 ans',
    },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Gregory', 'Erwann'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: 'Veuillez notez vos allergies ici.',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: true,
      after: true,
    },
  },
  {
    id: 'mrmrsd',
    name: 'Patricia et Thierry',
    people: ['Patricia', 'Thierry'],
    ages: { Patricia: '18 - 75 ans', Thierry: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'jeanluc',
    name: 'Jean-Luc',
    people: ['Jean-Luc'],
    ages: { 'Jean-Luc': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      "Tu as la question automatique sur ta présence à la cérémonie religieuse même si elle risquerait d'être râtée sans toi ! ;)",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'lelandais',
    name: 'Christine et René',
    people: ['Christine', 'René'],
    ages: { Christine: '18 - 75 ans', René: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'annick',
    name: 'Annick',
    people: ['Annick'],
    ages: { Annick: '75 ans et +' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'sylvie',
    name: 'Sylvie',
    people: ['Sylvie'],
    ages: { Sylvie: '18 - 75 ans' },
    plus1Invited: true,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'mariawojtek',
    name: 'Maria, Wojciech, Lucien et Teodor',
    people: ['Maria', 'Wojciech', 'Lucien', 'Teodor'],
    ages: {
      Maria: '18 - 75 ans',
      Wojciech: '18 - 75 ans',
      Lucien: '0 - 3 ans',
      Teodor: '0 - 3 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Lucien', 'Teodor'],
    placeholderComment:
      'Merci beaucoup pour l’invitation :relaxed: on sera très heureux de pouvoir passer cet moment important et magique avec vous et vos proches :relaxed:\nBisous à vous 3 :upside_down_face: :kissing_heart:\nMaria et Wojtek :relaxed:',
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'marjf',
    name: 'Marjorie et Jean-François',
    people: ['Marjorie', 'Jean-François L.C'],
    ages: { Marjorie: '18 - 75 ans', 'Jean-François L.C': '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment:
      'Please write us a little something, whatever you want ! :)',
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'mrsbouche',
    name: 'Cathy et Christian',
    people: ['Cathy', 'Christian'],
    ages: { Cathy: '18 - 75 ans', Christian: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'ganou',
    name: 'Morgane, Antoine et Augustin',
    people: ['Morgane', 'Antoine F', 'Augustin'],
    ages: {
      Morgane: '18 - 75 ans',
      'Antoine F': '18 - 75 ans',
      Augustin: '4 - 12 ans',
    },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: true,
    children: ['Augustin'],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
  {
    id: 'labarbiniere',
    name: 'Guy et Brigitte',
    people: ['Guy', 'Brigitte'],
    ages: { Guy: '18 - 75 ans', Brigitte: '18 - 75 ans' },
    plus1Invited: false,
    plus1Name: '',
    questionOnChildren: false,
    children: [],
    placeholderComment: "Un petit message pour qu'on se prépare au mieux ?",
    placeholderAllergies: '',
    isAnswered: true,
    invitedTo: {
      cityHall: false,
      church: true,
      wineReception: true,
      party: false,
      after: false,
    },
  },
]
